VisualResume::VisualResume(
  titles.left = c("","Amber Podmore, Temporary Accomadation Move-on Officer",  ""),
  titles.right = c("", "", ""),
  titles.left.cex = c(1,  4, 1),
  timeline.labels = c("Education", "Employment"),
  timeline = data.frame(title = c("Bury College", "University of Chester", "Customer service assistant",
                                  "Sales processor", "Tenancy Sustainment", "Temporary Accomadation"),
                        sub = c("4 A-levels", "BSc, Business", "Universal Studies, FL",
                                "Penthouse Carpets", "Guiness Partnership", "Oldham Council"),
                        start = c(2008.75, 2011.75, 2015.5, 2015.85,  2016,
                                  2020.25),
                        end = c(2011.75, 2015.5, 2015.85, 2016, 2020.25,
                                2022),
                        side = c(1, 0, 1, 0, 1, 0)),
  milestones = data.frame(title = c("BA"),
                          sub = c("Math/\nFrench", "Applied\nStatistics", 
                                  "Statistics"),
                          year = c(0, 0, 0)),
  events = data.frame(year = c(2016.75, 2016.25, 2020.05),
                      title = c("Idenetified for head start programme",
                                "Employee of the month",
                                "Another one")),
  interests = list("Clients" = c(rep("Pediatrics", 4), "Families",
                           rep("Wider\nSystems", 3), rep("Young Adults", 1)), 
                   "Neuopsychology" = c(rep("Functional\n Symptoms", 1), 
                                    rep("Stroke", 2), rep("Brain\nInjury", 1), 
                                    rep("Capacity", 2)),
                   "Therapy" = c(rep("Interoception", 8), rep("Effectiveness", 2), 
                                  rep("Reflective\nPractice", 6), rep("systemic\nWorking", 5))),
  year.steps = 1
)